export type MemberType = "member" | "mentor";

export interface MemberProfile {
  id: string;
  name: string;
  roleId: string;
  roleEn: string;
  type: MemberType;
  imagePlaceholder: string;
  majorId?: string;
  majorEn?: string;
  universityId?: string;
  universityEn?: string;
  achievementsId?: string[];
  achievementsEn?: string[];
}

export const members: MemberProfile[] = [
  {
    id: "t-01",
    name: "Rizkiyah Ananda Mutmainnah",
    roleId: "President",
    roleEn: "President",
    type: "member",
    imagePlaceholder: "/images/members/Rizkiyah Ananda President.jpeg",
  },
  {
    id: "t-02",
    name: "Andi Putri Cahaya Ningrum",
    roleId: "Head of Media",
    roleEn: "Head of Media",
    type: "member",
    imagePlaceholder: "/images/members/Andi Putri_Head of Media.JPG",
  },
  {
    id: "t-03",
    name: "Andi Shifa Salsabilla",
    roleId: "Head Of HRD",
    roleEn: "Head Of HRD",
    type: "member",
    imagePlaceholder: "/images/members/Andi Shifa Salsabillah_Head Of HRD.JPG",
  },
  {
    id: "t-04",
    name: "Fathinah Nur Jannah",
    roleId: "Head Of R&E",
    roleEn: "Head Of R&E",
    type: "member",
    imagePlaceholder: "/images/members/Fathinah N Jannah_Head Of R&E.JPG",
  },
  {
    id: "m-01",
    name: "Annisa Aulia Maharani",
    roleId: "Sekretaris",
    roleEn: "Secretary",
    type: "member",
    imagePlaceholder: "/images/members/Annisa A Maharani_Secretary.JPG",
  },
  {
    id: "m-02",
    name: "Nur Qalby Salsabila",
    roleId: "Bendahara",
    roleEn: "Treasurer",
    type: "member",
    imagePlaceholder: "/images/members/Nur Qalby Salsabila_Bendahara.JPG",
  },
  {
    id: "m-03",
    name: "Angel Eleonor Theophilina Manuputty",
    roleId: "Staff HRD",
    roleEn: "Staff HRD",
    type: "member",
    imagePlaceholder: "/images/members/Angel E.Th Manuputty_Staff HRD.JPG",
  },
  {
    id: "m-04",
    name: "Safrina Inayah",
    roleId: "Staff HRD",
    roleEn: "Staff HRD",
    type: "member",
    imagePlaceholder: "/images/members/Safrina Inayah_Staff HRD.JPG",
  },
  {
    id: "m-05",
    name: "Aulia Khairunnisa Isman",
    roleId: "Staff Media",
    roleEn: "Staff Media",
    type: "member",
    imagePlaceholder: "/images/members/Aulia K Isman_Staff Media.JPG",
  },
  {
    id: "m-06",
    name: "Najwa Putri Larasati",
    roleId: "Staff Media",
    roleEn: "Staff Media",
    type: "member",
    imagePlaceholder: "/images/members/Najwa P Larasati_Staff Media.JPG",
  },
  {
    id: "m-07",
    name: "Nasywa Elysia Apsari",
    roleId: "Staff Media",
    roleEn: "Staff Media",
    type: "member",
    imagePlaceholder: "/images/members/Nasywa E Apsari_Staff Media.JPG",
  },
  {
    id: "m-08",
    name: "Nur Fadilah S. Jaga",
    roleId: "Staff Media",
    roleEn: "Staff Media",
    type: "member",
    imagePlaceholder: "/images/members/Nur F S Jaga_Staff Media.JPG",
  },
  {
    id: "m-09",
    name: "Dhiska Dwi Hermalia H",
    roleId: "Staff Program",
    roleEn: "Staff Program",
    type: "member",
    imagePlaceholder: "/images/members/Dhiska D Hermalia H_Staff Program.JPG",
  },
  {
    id: "m-10",
    name: "Mevie Heatubun",
    roleId: "Staff Program",
    roleEn: "Staff Program",
    type: "member",
    imagePlaceholder: "/images/members/Mevie Heatubun_Staff program.jpg",
  },
  {
    id: "m-11",
    name: "Putri Atiqah Rana",
    roleId: "Staff Program",
    roleEn: "Staff Program",
    type: "member",
    imagePlaceholder: "/images/members/Putri Atiqah Rana_Staff Program.jpeg",
  },
  {
    id: "m-12",
    name: "Shafiyyah Nur Fadhilah Salandra",
    roleId: "Staff Program",
    roleEn: "Staff Program",
    type: "member",
    imagePlaceholder: "/images/members/Shafiyyah N F Salandra_Staff Program.JPG",
  },
  {
    id: "m-13",
    name: "Nurul Azizah Rahman Marasabessy",
    roleId: "Staff R&E",
    roleEn: "Staff R&E",
    type: "member",
    imagePlaceholder: "/images/members/Nurul Marasabessy_Staff RE.JPG",
  },
  {
    id: "m-14",
    name: "Sabina Juniar Tutupoho",
    roleId: "Staff R&E",
    roleEn: "Staff R&E",
    type: "member",
    imagePlaceholder: "/images/members/Sabina J. Tutupoho_Staff R&E.JPG",
  },
  {
    id: "m-15",
    name: "Dinah Zhafirah",
    roleId: "Staff HRD",
    roleEn: "Staff HRD",
    type: "member",
    imagePlaceholder: "/images/members/Dinah Zhafirah_Staff HRD.JPG",
  },
  {
    id: "m-16",
    name: "Vashajadyah Al Fadillah Ahmad",
    roleId: "Head Of Program",
    roleEn: "Head Of Program",
    type: "member",
    imagePlaceholder: "/images/members/Vashajadyah A F Ahmad_Head Of Program.JPG",
  },
  {
    id: "m-17",
    name: "Ikha Hilwa R Khaliky",
    roleId: "Staff Media",
    roleEn: "Staff Media",
    type: "member",
    imagePlaceholder: "/images/members/IKHA Hilwa R. Khaliky_ Staff Media.JPG",
  },
  {
    id: "mentor-01",
    name: "Arifah Deswina",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Arifah Deswina_Mentor.png",
    majorId: "Teknik Informatika",
    majorEn: "Informatics Engineering",
    universityId: "Universitas Hasanuddin",
    universityEn: "Hasanuddin University",
    achievementsId: [
      "Awardee Young Leaders for Indonesia (YLI) Wave 17 by Mckinsey & Co.",
      "Awardee beasiswa riset Badan Amil Zakat Nasional (BAZNAS) 2025-2026",
      "The Generation IMPACT Student Ambassador by Schneider Electric 2024-2025",
    ],
    achievementsEn: [
      "Awardee Young Leaders for Indonesia (YLI) Wave 17 by Mckinsey & Co.",
      "Awardee of the BAZNAS research scholarship 2025-2026",
      "The Generation IMPACT Student Ambassador by Schneider Electric 2024-2025",
    ],
  },
  {
    id: "mentor-02",
    name: "Zikra Nagasuri",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Zikra Nagasuri_Mentor.png",
    majorId: "Teknik Lingkungan",
    majorEn: "Environmental Engineering",
    universityId: "Universitas Hasanuddin",
    universityEn: "Hasanuddin University",
    achievementsId: [
      "Participant of Pre-ETIC Program – Kanazawa University, Japan & Awardee of JASSO Scholarship (2025/2026)", 
      "1st Place Winner – Scientific Writing Competition HLHS, PT IMIP (2025)",
      "Funded Research Awardee – PKM-RE (Program Kreativitas Mahasiswa – Riset Eksakta) (2024)",
    ],
    achievementsEn: [
      "Participant of Pre-ETIC Program – Kanazawa University, Japan & Awardee of JASSO Scholarship (2025/2026)", 
      "1st Place Winner – Scientific Writing Competition HLHS, PT IMIP (2025)",
      "Funded Research Awardee – PKM-RE (Program Kreativitas Mahasiswa – Riset Eksakta) (2024)",
    ],
  },
  {
    id: "mentor-03",
    name: "Khadija Karepesina",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Khadija Karapesina_Mentor.png",
    majorId: "Teknik Indusri",
    majorEn: "Industrial Engineering",
    universityId: "Universitas Pattimura",
    universityEn: "Pattimura University",
    achievementsId: [
      "Google Ambassador", 
      "Mapres Unpattimurra",
      "PMM Batch 4",
    ],
    achievementsEn:  [
      "Google Ambassador", 
      "Mapres Unpattimurra",
      "PMM Batch 4",
    ],
  },
  {
    id: "mentor-04",
    name: "Renny Rosa",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Renny Rosa_Mentor.png",
    majorId: "Hubungan Internasional",
    majorEn: "International Relations",
    universityId: "Universitas Kristen Indonesia",
    universityEn: "Universitas Kristen Indonesia",
    achievementsId: [
      "Regional Women's Committee WSCF AP (2025-2027)",
      "Pembicara dalam Seminar 'Jaga Perempuan Indonesia' sub tema : “Merekam Jejak Perempuan Merebut Ruang dan Partisipasi Publik di Indonesia: Dari Kolonialisme hingga Era Digital” oleh DPP BMI Tahun 2026",
      "Pelatihan Fasilitator Perempuan dengan Tema 'Ruang Aman untuk Perempuan' DPP GAMKI Tahun 2025",
    ],
    achievementsEn: [
      "Regional Women's Committee, WSCF AP (2025–2027)",
      "Speaker at the 'Protect Indonesian Women' (Jaga Perempuan Indonesia) Seminar; Sub-theme: “Tracing Women’s Footsteps in Reclaiming Space and Public Participation in Indonesia: From Colonialism to the Digital Era,” organized by the BMI Central Board (2026)",
      "Women’s Facilitator Training; Theme: “Safe Spaces for Women,” organized by the GAMKI Central Board (2025)",
    ],
  },
  {
    id: "mentor-05",
    name: "Andi Al Amanda Ismarani Divanthy",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Andi Al Amanda Ismarani Divanthy_Mentor.png",
    majorId: "Teknik Infrastruktur Lingkungan",
    majorEn: "Environmental Infrastructure Engineering",
    universityId: "Universitas Gadjah Mada",
    universityEn: "Gadjah Mada University",
    achievementsId: [
      "Top 3 Mahasiswa Berprestasi Fakultas Teknik UGM Tahun 2026",
      "Pemimpin Umum CLAPEYRON MEDIA: Badan Pers Mahasiswa Teknik Sipil UGM",
      "Awardee Beasiswa Amartha STEAM Fellowship Tahun 2025",
      "Awardee Kennedy Lugar-Youth Exchange and Study (KL-YES) YP 21/22 oleh Yayasan Bina Antarbudaya",
      "Alumna Better Understanding for Better World (BUBW) Tahun 2026",
    ],
    achievementsEn: [
      "Top 3 Outstanding Students, Faculty of Engineering, UGM (2026)",
      "Editor-in-Chief of CLAPEYRON MEDIA: Civil Engineering Student Press Body, UGM",
      "Awardee of the Amartha STEAM Fellowship Scholarship (2025)",
      "Awardee of the Kennedy Lugar Youth Exchange and Study (KL-YES) YP 21/22 by Yayasan Bina Antarbudaya",
      "Alumna of Better Understanding for Better World (BUBW) (2026)",
    ],
  },
  {
    id: "mentor-06",
    name: "Azzahra Aurelya Shodan Razak",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Azzahra Aurelya Shodan Razak_Mentor.PNG",
    majorId: "Pendidikan Dokter",
    majorEn: "Medical Education",
    universityId: "Universitas Hasanuddin",
    universityEn: "Hasanuddin University",
    achievementsId: [
      "Mahasiswa Berprestasi 2 Universitas Hasanuddin Tahun 2026",
      "Peraih 2 Medali Emas Pekan Ilmiah Mahasiswa Nasional",
      "Penerima Pendanaan Program Kreativitas Mahasiswa Skema Riset Eksakta 2024 dan 2025",
      "Awardee Kennedy-Lugar Youth Exchange and Study (KL-YES) 2021-2022",
    ],
    achievementsEn: [
      "2nd Outstanding Student of Hasanuddin University (2026)",
      "Recipient of 2 Gold Medals at the National Student Scientific Week",
      "Funded Awardee of the Student Creativity Program, Exact Sciences Research Scheme (PKM-RE) in 2024 and 2025",
      "Awardee of the Kennedy-Lugar Youth Exchange and Study (KL-YES) 2021-2022",
    ],
  },
  {
    id: "mentor-07",
    name: "Salsabila A Salloko",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Salsabila A Salloko_Mentor.png",
    majorId: "Ilmu Komunikasi",
    majorEn: "Communication Science",
    universityId: "Universitas Hasanuddin",
    universityEn: "Hasanuddin University",
    achievementsId: [
      "Best Presentator of Campus Leaders Program Bakrie Center Foundation 2025",
      "Public Speaker, MC, Moderator, Reporter for 50+ event",
      "Voice over talent for +10 brand ads",
      "Announcer at radio station in Makassar",
      "Grab Campus Ambassador",
      "Brand Ambassador AIESEC in Unhas",
    ],
    achievementsEn: [
      "Best Presenter of the Campus Leaders Program, Bakrie Center Foundation (2025)",
      "Public Speaker, MC, Moderator, and Reporter for 50+ events",
      "Voice-over talent for 10+ brand advertisements",
      "Announcer at a radio station in Makassar",
      "Grab Campus Ambassador",
      "Brand Ambassador of AIESEC in Unhas",
    ],
  },
  {
    id: "mentor-08",
    name: "Sheila Imanuella Thenu",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Sheila Imanuella Thenu_Mentor.png",
    majorId: "Teknik Perminyakan",
    majorEn: "Petroleum Engineering",
    universityId: "Universitas Pattimura",
    universityEn: "Pattimura University",
    achievementsId: [
      "Penerima Skema Pendanaan Program Kreativitas Mahasiswa - Riset Eksakta (PKM-RE) Tahun 2024",
      "Pembicara pada Welcoming Dinner dan Opening Moments The Asia Grassroots Forum 2025 sebagai perwakilan Penerima Amartha STEAM & Frontier Fellowship dan Perempuan Muda dari Indonesia Bagian Timur",
      "Harapan IV Duta Bahasa Nasional Tahun 2025",
      "President Society of Petroleum Engineers Pattimura University Student Chapter 2026-2027",
    ],
    achievementsEn: [
      "Recipient of the Student Creativity Program Funding Scheme - Exact Sciences Research (PKM-RE) in 2024",
      "Speaker at the Welcoming Dinner and Opening Moments of The Asia Grassroots Forum 2025 as a representative of Amartha STEAM & Frontier Fellowship awardees and young women from Eastern Indonesia",
      "4th Runner-Up of the National Language Ambassador 2025",
      "President of the Society of Petroleum Engineers, Pattimura University Student Chapter (2026-2027)",
    ],
  },
  
];
